In [1]:
import numpy as np
a=np.random.rand(3,3)
a

array([[0.05589427, 0.56594676, 0.96285257],
       [0.5711861 , 0.84851339, 0.44426509],
       [0.07955144, 0.88052495, 0.86909675]])

In [2]:
b=np.arange(2,8).reshape(2,3)
b

array([[2, 3, 4],
       [5, 6, 7]])

In [3]:
np.ndim(b)

2

In [4]:
#mathematical functions

np.sum(b)

np.int64(27)

In [5]:
a=np.array([[1,5,9],[8,2,1]])
np.ndim(a)

2

In [6]:
np.random.randint(15,25,5)

array([23, 19, 16, 23, 22], dtype=int32)

In [7]:
np.random.randint(3,5,20)

array([4, 3, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3, 4, 4, 3, 4, 3, 4, 4, 4],
      dtype=int32)

In [8]:
np.vstack( a)

array([[1, 5, 9],
       [8, 2, 1]])

In [9]:
np.hstack(a)

array([1, 5, 9, 8, 2, 1])

In [10]:
np.random.normal(3,5,20)

array([ 2.54822674,  1.94371979,  2.14080456, 13.31171343, -8.47701769,
        2.03140131,  3.01237126,  8.79801522,  5.87698693, -1.44630888,
       -1.25971468, -5.32921732, -1.09277958,  1.37800751,  4.99938921,
       -4.94811327, 13.00592868,  6.3463528 , -2.26603884, -2.1828882 ])

In [11]:
np.max(a)

np.int64(9)

In [12]:
np.min(a)

np.int64(1)

In [13]:
np.median(a)

np.float64(3.5)

In [14]:
np.log(a)

array([[0.        , 1.60943791, 2.19722458],
       [2.07944154, 0.69314718, 0.        ]])

In [15]:
np.sqrt(a)

array([[1.        , 2.23606798, 3.        ],
       [2.82842712, 1.41421356, 1.        ]])

In [16]:
a

array([[1, 5, 9],
       [8, 2, 1]])

In [17]:
np.std(a)

np.float64(3.2489314482696545)

In [18]:
np.exp(a)

array([[2.71828183e+00, 1.48413159e+02, 8.10308393e+03],
       [2.98095799e+03, 7.38905610e+00, 2.71828183e+00]])

In [19]:
f=np.array([3,5,6])
f[2]

np.int64(6)

In [20]:
a

array([[1, 5, 9],
       [8, 2, 1]])

In [21]:
a

array([[1, 5, 9],
       [8, 2, 1]])

In [22]:
b

array([[2, 3, 4],
       [5, 6, 7]])

In [23]:
b[1,1]

np.int64(6)

In [24]:
c=np.array([[[1,2,3],[5,4,8]],[[11,34,45],[22,13,22]]])
c

array([[[ 1,  2,  3],
        [ 5,  4,  8]],

       [[11, 34, 45],
        [22, 13, 22]]])

In [25]:
c[1,0:2,1:3]

array([[34, 45],
       [13, 22]])

In [26]:
m=np.array([1,2,3])
d=np.array([[4],[5],[6]])
s=m+d
s

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [27]:
s.flatten()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [28]:
s.ravel()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [29]:
import pandas as pd
d=pd.read_csv(r"C:\Users\Mohan\Downloads\pokemon.csv")
d

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [30]:
d.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [31]:
d.tail()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [32]:
d.columns

Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='object')

In [33]:
d.columns[d.isna().any()]

Index(['height_m', 'percentage_male', 'type2', 'weight_kg'], dtype='object')

In [34]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    object
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    object
 24  classfication      801 non-null    object
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    object
 30  name               801 non-null    object
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    object
 37  type2              417 non-null    object
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), object(7)
memory usage: 256.7+ KB

In [35]:
#null value

d['height_m']=d["height_m"].fillna(d["height_m"].median())
d['height_m']

0      0.7
1      1.0
2      2.0
3      0.6
4      1.1
      ...
796    9.2
797    0.3
798    5.5
799    2.4
800    1.0
Name: height_m, Length: 801, dtype: float64

In [36]:
d["height_m"].unique()

array([ 0.7,  1. ,  2. ,  0.6,  1.1,  1.7,  0.5,  1.6,  0.3,  1.5,  1.2,
        3.5,  0.4,  0.8,  1.3,  0.9,  1.4,  1.9,  1.8,  8.8,  2.2,  6.5,
        2.5,  2.1,  4. ,  2.3,  0.2,  9.2,  5.2,  3.8, 14.5,  2.7,  6.2,
        4.5,  7. ,  2.4,  5.4,  4.2,  3.7,  3.2,  3.3,  0.1,  2.6,  2.8,
        2.9,  3. ,  5.8,  5. ,  3.9,  3.4,  5.5])

In [39]:
d["type2"]=d["type2" ].fillna(d["type2" ].mode()[0])
d["type2"]

0      poison
1      poison
2      poison
3      flying
4      flying
        ...
796    flying
797     steel
798    dragon
799    flying
800     fairy
Name: type2, Length: 801, dtype: object

In [41]:
d["type2"].unique()

array(['poison', 'flying', 'dark', 'electric', 'ice', 'ground', 'fairy',
       'grass', 'fighting', 'psychic', 'steel', 'fire', 'rock', 'water',
       'dragon', 'ghost', 'bug', 'normal'], dtype=object)